"""set server_defaults for active and staff status

Revision ID: 84e90bb5b8b6
Revises: 450b9ec4f18d
Create Date: 2024-01-14 15:23:44.554400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e90bb5b8b6'
down_revision: Union[str, None] = '450b9ec4f18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
