"""create base tables

Revision ID: 8fa1e6da94a1
Revises: 
Create Date: 2024-01-15 08:49:08.114284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa1e6da94a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auctions',
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_description', sa.String(), nullable=False),
    sa.Column('item_category', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('current_bid', sa.Float(), server_default=sa.text('0.00'), nullable=False),
    sa.Column('reserve_status', sa.Enum('Reserve', 'No Reserve', name='reserve_status_options'), nullable=False),
    sa.Column('reserve_price', sa.Float(), server_default=sa.text('0.00'), nullable=False),
    sa.Column('auction_status', sa.Enum('Ongoing', 'Sold', 'Cancelled', 'Reserve price not met', name='auction_status_options'), nullable=True),
    sa.Column('seller', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_category'], ['item_categories.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('auction_id')
    )
    op.create_table('auction_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_description', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.auction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('bids',
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('bidder_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.auction_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bidder_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bid_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    op.drop_table('auction_images')
    op.drop_table('auctions')
    op.drop_table('users')
    op.drop_table('item_categories')
    # ### end Alembic commands ###
