name: Build and Deploy

on: 
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'develop'

jobs:
    build:
        environment:
            name: afribids-testing
        env:
            POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
            TEST_DATABASE_NAME: ${{ secrets.TEST_DATABASE_NAME }}
            POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
            POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
            BID_JUMP: ${{ secrets.BID_JUMP }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AFRIBIDS_IMAGES_BUCKET: ${{ secrets.AFRIBIDS_IMAGES_BUCKET }}
            CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
            CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: ${{secrets.POSTGRES_USERNAME}}
                    POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
                    POSTGRES_DB: ${{secrets.TEST_DATABASE_NAME}}
                    
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        
        runs-on: ubuntu-latest

        steps:
            - name: get repo
              uses: actions/checkout@v4

            - name: install python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: '3.11' 

            - name: update pip
              run: python -m pip install --upgrade pip

            - name: install dependencies
              run: pip install -r requirements.txt

            - name: run tests with pytest
              run: |
                pip install pytest
                pytest -v